version: 2

node_test_env: &node_test_env
  NPM_CONFIG_UNSAFE_PERM: true

node_unit_tests: &node_unit_tests
  steps:
    - checkout
    - run:
        name: Install Root Dependencies
        command: npm install --ignore-scripts
    - run:
        name: Unit tests
        command: npm run test

jobs:
  node8:
    docker:
      - image: node:8
        environment: *node_test_env
    <<: *node_unit_tests
  node10:
    docker:
      - image: node:10
        environment: *node_test_env
    <<: *node_unit_tests
  node12:
    docker:
      - image: node:12
        environment: *node_test_env
    <<: *node_unit_tests
  node14:
    docker:
      - image: node:14
        environment: *node_test_env
    <<: *node_unit_tests

workflows:
  version: 2
  build:
    jobs:
      - node8
      - node10
      - node12
      - node14
